# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PromiseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PromiseDemo
  pod "PromiseKit", "~> 6.8"
  pod "PromiseKit/CoreLocation"
  pod 'SnapKit'

end
